# Generated by Django 5.0.7 on 2025-05-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_quiz_answer_choices_and_more'),
        ('progress', '0004_quizattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='content.quiz'),
        ),
    ]
