# Generated by Django 5.0.7 on 2025-05-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
