# Generated by Django 5.0.7 on 2025-05-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='KcsePastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('paper_type', models.CharField(choices=[('Paper 1', 'Paper 1'), ('Paper 2', 'Paper 2'), ('Paper 3', 'Paper 3')], max_length=50)),
                ('file', models.FileField(upload_to='kcse_pastpapers/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
