# Generated by Django 5.0.7 on 2025-06-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0003_examfilemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
