# Generated by Django 5.2.1 on 2025-05-09 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer_choices',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_a',
            field=models.CharField(default='Study of chemicals', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_b',
            field=models.CharField(default='Study of chemicals', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_c',
            field=models.CharField(default='Study of chemicals', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_d',
            field=models.CharField(default='Study of chemicals', max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='content.lesson'),
        ),
    ]
