# Generated by Django 5.0.7 on 2025-05-14 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_remove_thread_receiver_remove_thread_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussions.privatemessage'),
        ),
    ]
